// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK2W9xmFoa9EqrHYaiX_jsczJeTiH64yc',
    appId: '1:295282834671:web:0418cf734441665e326f1a',
    messagingSenderId: '295282834671',
    projectId: 'battleship-b6b9f',
    authDomain: 'battleship-b6b9f.firebaseapp.com',
    storageBucket: 'battleship-b6b9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrjvW17xwugGS2C2E0YkhReNUSs06nFE',
    appId: '1:295282834671:android:e6a4ef8dd0f6126f326f1a',
    messagingSenderId: '295282834671',
    projectId: 'battleship-b6b9f',
    storageBucket: 'battleship-b6b9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1mh9ZaDVBHr0NKXYCJ2jyJnGbG0GVt4',
    appId: '1:295282834671:ios:44c94c08b94e3760326f1a',
    messagingSenderId: '295282834671',
    projectId: 'battleship-b6b9f',
    storageBucket: 'battleship-b6b9f.appspot.com',
    iosBundleId: 'com.example.battleship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1mh9ZaDVBHr0NKXYCJ2jyJnGbG0GVt4',
    appId: '1:295282834671:ios:73b7e6ee33c55b9a326f1a',
    messagingSenderId: '295282834671',
    projectId: 'battleship-b6b9f',
    storageBucket: 'battleship-b6b9f.appspot.com',
    iosBundleId: 'com.example.battleship.RunnerTests',
  );
}
